### ISSUE TITLE
Unclear error message in reframe_event

### ISSUE THREAD

**Issue by KrisanatA** [cynthiahqy/ggtilecal#3]
Unclear error message for this part: 

`stopifnot(nrow(dups) == 0) # rowwise grouping didnt work`

**Comment by cynthiahqy** [comment]
add `id_cols` arg and make the error message clearer with ac0b093db12d6165125590e07cd860194a861769

**Comment by cynthiahqy** [comment]
@KrisanatA next time link the code rather than copy-paste
<img width="868" alt="image" src="https://github.com/cynthiahqy/ggtilecal/assets/29718979/2b4353a8-5d89-46b1-8428-0ec0f72caa6c">
